insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (1, 69, 'Kagoshima Women''s College', '8/25/2020', 2.0, 'Dr', 'Consumer Services', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (2, 3, 'Universidad Latinoamericana', '7/27/2020', 2.6, 'Dr', 'n/a', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (3, 34, 'Grinnell College', '3/6/2020', 2.2, 'Mrs', 'Miscellaneous', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (4, 3, 'Karaganda State Buketov University', '7/9/2020', 1.2, 'Honorable', 'n/a', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (5, 3, 'Udmurt State University', '12/12/2019', 2.9, 'Honorable', 'Health Care', 'Transportation');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (6, 53, 'Emmanuel College', '3/2/2020', 2.5, 'Mr', 'n/a', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (7, 64, 'University of South Carolina - Spartanburg', '9/21/2020', 1.6, 'Dr', 'Consumer Services', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (8, 67, 'Universidade Estadual do Norte Fluminense', '6/28/2020', 1.7, 'Ms', 'Technology', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (9, 70, 'Universidad de La Sabana', '10/16/2020', 2.6, 'Dr', 'Miscellaneous', 'Miscellaneous');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (10, 85, 'Blekinge Institute of Technology', '7/25/2020', 3.6, 'Mr', 'Consumer Non-Durables', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (11, 4, 'Virginia Polytechnic Institute and State University (Virginia Tech)', '5/3/2020', 3.1, 'Honorable', 'n/a', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (12, 92, 'Royal Free Hospital School of Medicine, University of London', '2/11/2020', 2.4, 'Mr', 'n/a', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (13, 60, 'National Mining University', '3/22/2020', 2.3, 'Rev', 'Health Care', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (14, 14, 'Hanoi National Economics University', '12/29/2019', 1.1, 'Mrs', 'Health Care', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (15, 29, 'Instituto Universitario de Ciencias de la Salud Fundación H.A. Barceló', '9/11/2020', 1.2, 'Ms', 'Finance', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (16, 13, 'Christopher Newport University', '11/23/2019', 2.9, 'Rev', 'n/a', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (17, 59, 'Eberhard-Karls-Universität Tübingen', '6/27/2020', 3.4, 'Ms', 'n/a', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (18, 9, 'Florida Christian College', '11/12/2019', 1.5, 'Mr', 'Energy', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (19, 26, 'Ben-Gurion University of the Negev', '10/31/2019', 3.4, 'Mrs', 'Consumer Services', 'Transportation');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (20, 7, 'University of Zadar', '9/29/2020', 2.6, 'Ms', 'Basic Industries', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (21, 39, 'Manhattan School of Music', '7/31/2020', 1.2, 'Honorable', 'Basic Industries', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (22, 27, 'University of Chicago', '5/12/2020', 3.0, 'Ms', 'Technology', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (23, 20, 'American Conservatory Theater', '8/4/2020', 2.5, 'Honorable', 'Finance', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (24, 100, 'Universitas Bengkulu', '6/1/2020', 2.6, 'Honorable', 'Finance', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (25, 68, 'Massachusetts College of Pharmacy and Allied Health Sciences', '7/15/2020', 2.1, 'Dr', 'Consumer Services', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (26, 56, 'Université Mohammed Ier', '11/6/2019', 2.7, 'Mr', 'Energy', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (27, 21, 'Zhejiang Normal University', '5/26/2020', 3.5, 'Mr', 'Health Care', 'Consumer Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (28, 19, 'Maine Maritime Academy', '6/10/2020', 3.2, 'Mrs', 'Health Care', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (29, 88, 'Lakehead University', '4/20/2020', 2.7, 'Mr', 'n/a', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (30, 5, 'Alfred Nobel University of Economics and Law ', '12/21/2019', 3.6, 'Dr', 'Health Care', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (31, 17, 'Glion Institute of Higher Education', '1/23/2020', 1.0, 'Honorable', 'Consumer Non-Durables', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (32, 1, 'Michigan Technological University', '7/15/2020', 2.0, 'Mrs', 'n/a', 'Energy');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (33, 91, 'Arak University of Medical Sciences', '4/11/2020', 1.2, 'Honorable', 'n/a', 'Energy');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (34, 95, 'Bellin College of Nursing', '5/22/2020', 3.4, 'Rev', 'Capital Goods', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (35, 19, 'Northern Kentucky University', '12/4/2019', 1.3, 'Mr', 'Finance', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (36, 24, 'Beijing Information Science and Technology University', '7/11/2020', 3.4, 'Rev', 'n/a', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (37, 51, 'Universidad Laica "Eloy Alfaro" de Manabi', '3/1/2020', 1.5, 'Mr', 'Health Care', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (38, 51, 'Nara Sangyo University', '10/16/2020', 3.0, 'Mr', 'Consumer Durables', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (39, 12, 'Al Imam Al-Ouzai University', '2/28/2020', 2.3, 'Rev', 'Finance', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (40, 21, 'Universitas Pekalongan', '3/11/2020', 1.8, 'Ms', 'Basic Industries', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (41, 70, 'Clemson University', '2/1/2020', 4.0, 'Ms', 'Finance', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (42, 40, 'Universität Graz', '2/16/2020', 2.7, 'Mrs', 'Energy', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (43, 100, 'Imam Khomeini International University', '8/10/2020', 1.2, 'Rev', 'Consumer Non-Durables', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (44, 61, 'Yerevan State Medical University', '12/26/2019', 4.0, 'Mrs', 'Technology', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (45, 92, 'National University of Internal Affairs', '9/13/2020', 1.9, 'Mrs', 'Public Utilities', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (46, 62, 'Gujarat Technological University Ahmedabad', '2/27/2020', 3.0, 'Mrs', 'Finance', 'Miscellaneous');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (47, 74, 'Technical University of Crete', '8/10/2020', 2.7, 'Mrs', 'n/a', 'Energy');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (48, 88, 'Middlebury College', '3/8/2020', 1.7, 'Ms', 'Finance', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (49, 81, 'Kazakhstan Institute of Management, Economics, and Strategic Research', '3/15/2020', 3.6, 'Rev', 'Consumer Non-Durables', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (50, 9, 'Morioka College', '4/17/2020', 3.8, 'Mrs', 'Consumer Services', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (51, 5, 'Udmurt State University', '9/5/2020', 3.8, 'Rev', 'Public Utilities', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (52, 32, 'École Nationale Supérieure d''Ingénieurs de Constructions Aéronautiques', '10/22/2020', 3.1, 'Rev', 'Consumer Services', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (53, 62, 'University of Nottingham, Malaysia Campus', '9/25/2020', 3.2, 'Mrs', 'Miscellaneous', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (54, 43, 'Moscow State University of Civil Engineering', '5/6/2020', 2.4, 'Dr', 'n/a', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (55, 17, 'Universidad Isaac Newton', '10/31/2019', 2.2, 'Dr', 'Finance', 'Miscellaneous');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (56, 82, 'Université Michel de Montaigne (Bordeaux III )', '8/24/2020', 3.6, 'Mr', 'Consumer Durables', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (57, 62, 'University of Development Alternative', '10/21/2020', 1.7, 'Mrs', 'n/a', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (58, 83, 'Moscow State University of Railway Transport', '3/27/2020', 1.7, 'Dr', 'Consumer Non-Durables', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (59, 34, 'Loma Linda University', '10/31/2019', 2.5, 'Mrs', 'Consumer Services', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (60, 79, 'Kotelawala Defence University', '5/16/2020', 3.1, 'Rev', 'Energy', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (61, 42, 'Lakehead University', '12/23/2019', 3.2, 'Honorable', 'Technology', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (62, 40, 'Universität Passau', '1/18/2020', 2.4, 'Rev', 'Consumer Services', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (63, 6, 'Sampurnanand Sanskrit University', '10/9/2020', 4.0, 'Ms', 'Technology', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (64, 48, 'Université d''Aix-Marseille III', '6/24/2020', 2.3, 'Mr', 'Consumer Services', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (65, 6, 'Shihezi University ', '2/26/2020', 2.7, 'Ms', 'Finance', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (66, 59, 'Danang College Of Technology', '1/24/2020', 3.3, 'Honorable', 'Finance', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (67, 61, 'Université Pierre et Marie Curie (Paris VI)', '9/12/2020', 2.3, 'Dr', 'Basic Industries', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (68, 96, 'Universidad Autónoma de Chihuahua', '9/28/2020', 2.4, 'Dr', 'Public Utilities', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (69, 6, 'Lane College', '9/11/2020', 3.5, 'Mrs', 'Finance', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (70, 29, 'Christian Brothers University', '3/31/2020', 2.0, 'Mr', 'Health Care', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (71, 96, 'Rand Graduate School of Policy Studies', '1/16/2020', 2.4, 'Ms', 'n/a', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (72, 44, 'Institute of Social Studies', '1/15/2020', 1.9, 'Ms', 'n/a', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (73, 62, 'Boise Bible College', '6/11/2020', 3.1, 'Mrs', 'Finance', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (74, 62, 'Shanghai TieDao University', '8/19/2020', 1.4, 'Mr', 'Public Utilities', 'Transportation');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (75, 60, 'Universidad Hispanoamericana', '3/9/2020', 3.8, 'Honorable', 'Public Utilities', 'Consumer Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (76, 38, 'Zahedan University of Medical Sciences', '5/8/2020', 3.2, 'Rev', 'Finance', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (77, 75, 'Hirosaki Gakuin University', '5/13/2020', 3.3, 'Mrs', 'Finance', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (78, 50, 'Nizhny Novgorod State Academy of Medicine', '9/24/2020', 3.1, 'Rev', 'n/a', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (79, 92, 'South Florida Bible College & Theological Seminary', '7/15/2020', 2.6, 'Mrs', 'Consumer Non-Durables', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (80, 18, 'California School of Professional Psychology - Fresno', '1/21/2020', 1.5, 'Honorable', 'Finance', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (81, 85, 'Universidade Metropolitana de Santos', '8/7/2020', 3.7, 'Rev', 'Finance', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (82, 35, 'Northwestern University of the Philippines', '11/25/2019', 1.1, 'Dr', 'Finance', 'Transportation');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (83, 81, 'Karachi Institute Of Economics And Technology', '1/1/2020', 3.3, 'Ms', 'n/a', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (84, 30, 'St. Petersburg State Pediatric Medical Academy', '8/21/2020', 3.0, 'Ms', 'n/a', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (85, 20, 'Colby-Sawyer College', '2/26/2020', 2.0, 'Rev', 'Consumer Services', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (86, 94, 'Islamic Azad University, Mashhad', '12/19/2019', 3.6, 'Dr', 'n/a', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (87, 77, 'Universite des Sciences Islamiques de Constantine', '5/28/2020', 4.0, 'Honorable', 'Health Care', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (88, 3, 'Institut Catholique de Toulouse', '11/30/2019', 3.3, 'Dr', 'Public Utilities', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (89, 18, 'Universidad de Zaragoza', '6/14/2020', 3.6, 'Rev', 'n/a', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (90, 50, 'Jawaharlal Nehru Centre for Advanced  Scientific Research', '1/17/2020', 1.3, 'Honorable', 'Consumer Non-Durables', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (91, 69, 'University of Ferrara', '12/27/2019', 2.4, 'Ms', 'Energy', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (92, 36, 'Benedictine University', '8/12/2020', 2.0, 'Rev', 'Health Care', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (93, 10, 'Catholic University of Pusan', '2/20/2020', 2.9, 'Mrs', 'Health Care', 'Energy');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (94, 26, 'Technische Universität Dresden', '2/6/2020', 2.0, 'Mrs', 'n/a', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (95, 43, 'University of Missouri - Saint Louis', '3/20/2020', 2.8, 'Rev', 'Energy', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (96, 22, 'National American University, Roseville', '7/19/2020', 3.6, 'Rev', 'n/a', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (97, 72, 'Universidad Autónoma de Querétaro', '7/18/2020', 2.4, 'Rev', 'Energy', 'Consumer Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (98, 68, 'Harbin Medical University', '3/23/2020', 2.4, 'Rev', 'Consumer Non-Durables', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (99, 47, 'Bharathiar University', '3/1/2020', 1.7, 'Honorable', 'n/a', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (100, 38, 'St. Anselm College', '4/29/2020', 1.9, 'Mr', 'Finance', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (101, 45, 'Meiji University', '10/17/2020', 2.4, 'Honorable', 'Consumer Services', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (102, 76, 'British Royal University', '1/17/2020', 3.3, 'Mrs', 'Public Utilities', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (103, 12, 'Mansoura University', '3/16/2020', 3.7, 'Honorable', 'Consumer Services', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (104, 99, 'TPM College', '4/22/2020', 3.1, 'Honorable', 'Finance', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (105, 52, 'Vlerick Leuven Gent Management School', '9/22/2020', 3.8, 'Honorable', 'Capital Goods', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (106, 52, 'Southeastern Louisiana University', '1/3/2020', 2.4, 'Rev', 'Health Care', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (107, 3, 'Islamic Azad University, Arak', '1/16/2020', 2.9, 'Honorable', 'Capital Goods', 'Miscellaneous');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (108, 70, 'Arizona State University, Downtown Phoenix Campus', '8/21/2020', 2.0, 'Mr', 'Capital Goods', 'Miscellaneous');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (109, 43, 'California Coast University', '8/14/2020', 3.1, 'Ms', 'n/a', 'Energy');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (110, 41, 'Universidade Católica de Salvador', '12/10/2019', 3.2, 'Honorable', 'Technology', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (111, 29, 'Capital University Law School', '5/23/2020', 3.5, 'Honorable', 'Consumer Services', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (112, 97, 'University of Arizona', '8/10/2020', 1.1, 'Rev', 'Finance', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (113, 20, 'Hogeschool West-Vlaanderen (TU)', '6/25/2020', 2.5, 'Rev', 'Capital Goods', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (114, 84, 'Fisher College', '10/18/2020', 2.9, 'Mr', 'Energy', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (115, 96, 'Lourdes College', '9/23/2020', 2.4, 'Mr', 'Consumer Non-Durables', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (116, 4, 'Daito Bunka University', '7/22/2020', 3.9, 'Ms', 'Finance', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (117, 99, 'University of North Carolina at Asheville', '5/2/2020', 2.5, 'Mrs', 'Health Care', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (118, 22, 'University of Kirkuk', '1/16/2020', 2.2, 'Mrs', 'n/a', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (119, 97, 'Glenville State College', '9/28/2020', 1.7, 'Rev', 'Technology', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (120, 94, 'Chiba University of Commerce', '11/7/2019', 3.0, 'Rev', 'Finance', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (121, 3, 'Deccan College Postgraduate and Research Institute', '11/30/2019', 3.8, 'Honorable', 'Miscellaneous', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (122, 25, 'Hochschule für Jüdische Studien Heidelberg', '3/19/2020', 2.2, 'Honorable', 'Finance', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (123, 33, 'Gdynia Maritime Academy', '6/15/2020', 3.1, 'Mr', 'Consumer Services', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (124, 11, 'Universidade Vale do Paraiba', '2/25/2020', 1.0, 'Rev', 'n/a', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (125, 25, 'National University of Arts', '4/14/2020', 3.1, 'Dr', 'Technology', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (126, 64, 'Intercollege', '8/1/2020', 3.1, 'Ms', 'Consumer Services', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (127, 40, 'Nippon Veterinary and Animalscience University', '11/10/2019', 3.8, 'Ms', 'Energy', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (128, 99, 'University of Bergen', '8/11/2020', 2.7, 'Mr', 'n/a', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (129, 6, 'Universidad de Cartago Florencio del Castillo', '8/19/2020', 1.6, 'Dr', 'Finance', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (130, 29, 'Coe College', '6/7/2020', 2.2, 'Dr', 'Consumer Non-Durables', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (131, 3, 'Technical University of Cracow', '4/7/2020', 1.6, 'Honorable', 'Health Care', 'Consumer Services');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (132, 93, 'Institute for Advanced Studies Lucca', '12/15/2019', 2.4, 'Ms', 'Consumer Services', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (133, 92, 'Ladoke Akintola University of Technology', '2/13/2020', 1.1, 'Rev', 'Basic Industries', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (134, 10, 'University of Crete', '11/25/2019', 2.2, 'Honorable', 'Consumer Services', 'Public Utilities');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (135, 80, 'Universitas Jember', '3/8/2020', 3.7, 'Mr', 'Finance', 'Health Care');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (136, 68, 'Third University of Rome', '7/13/2020', 3.2, 'Ms', 'Technology', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (137, 68, 'Dr. Babasaheb Ambedkar Marathwada Universtiy', '2/21/2020', 2.4, 'Honorable', 'Capital Goods', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (138, 46, 'University of Rajshahi', '2/17/2020', 2.7, 'Mrs', 'n/a', 'Energy');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (139, 28, 'The College of Santa Fe', '7/3/2020', 3.9, 'Dr', 'Finance', 'Consumer Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (140, 65, 'Arab Open University', '4/6/2020', 2.8, 'Mrs', 'Basic Industries', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (141, 90, 'Ross University Caribbean School of Medicine', '4/6/2020', 3.3, 'Ms', 'Technology', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (142, 55, 'Niigata College of Pharmacy', '6/14/2020', 3.0, 'Mr', 'Capital Goods', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (143, 50, 'University of Central Florida', '1/28/2020', 2.7, 'Dr', 'n/a', 'Finance');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (144, 44, 'Central Ostrobothnia University of Applied Sciences', '2/28/2020', 3.6, 'Honorable', 'Health Care', 'Capital Goods');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (145, 69, 'Concordia College, Seward', '4/21/2020', 2.6, 'Honorable', 'Technology', 'Consumer Non-Durables');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (146, 92, 'St. Petersburg State University', '8/28/2020', 3.3, 'Honorable', 'Capital Goods', 'Basic Industries');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (147, 53, 'University of Electro-Communications', '4/8/2020', 1.1, 'Dr', 'Consumer Durables', 'n/a');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (148, 99, 'James Madison University', '2/16/2020', 2.8, 'Dr', 'n/a', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (149, 81, 'Catholic University of Eastern Africa', '5/23/2020', 1.8, 'Honorable', 'Consumer Non-Durables', 'Technology');
insert into EDUCATION (E_ID, U_ID, Institution, Grad_date, GPA, Degree, Major, Minor) values (150, 100, 'Saint Louis University', '12/7/2019', 3.3, 'Rev', 'Health Care', 'Finance');
