insert into SKILL (S_ID, Skill_Name) values (1, 'VFX Supervision');
insert into SKILL (S_ID, Skill_Name) values (2, 'Gynecologic Surgery');
insert into SKILL (S_ID, Skill_Name) values (3, 'Class III Medical Devices');
insert into SKILL (S_ID, Skill_Name) values (4, 'OS/400');
insert into SKILL (S_ID, Skill_Name) values (5, 'FBT');
insert into SKILL (S_ID, Skill_Name) values (6, 'Smart Cards');
insert into SKILL (S_ID, Skill_Name) values (7, 'Kurzweil');
insert into SKILL (S_ID, Skill_Name) values (8, 'Site Planning');
insert into SKILL (S_ID, Skill_Name) values (9, 'Tcpdump');
insert into SKILL (S_ID, Skill_Name) values (10, 'Epistemology');
insert into SKILL (S_ID, Skill_Name) values (11, 'Document Review');
insert into SKILL (S_ID, Skill_Name) values (12, 'Shell Scripting');
insert into SKILL (S_ID, Skill_Name) values (13, 'ATG CSC');
insert into SKILL (S_ID, Skill_Name) values (14, 'Zoo');
insert into SKILL (S_ID, Skill_Name) values (15, 'Equity Research');
insert into SKILL (S_ID, Skill_Name) values (16, 'Ukulele');
insert into SKILL (S_ID, Skill_Name) values (17, 'VSTS');
insert into SKILL (S_ID, Skill_Name) values (18, 'Interactive TV');
insert into SKILL (S_ID, Skill_Name) values (19, 'PHP');
insert into SKILL (S_ID, Skill_Name) values (20, 'Vyatta');
insert into SKILL (S_ID, Skill_Name) values (21, 'Medical Writing');
insert into SKILL (S_ID, Skill_Name) values (22, 'VO');
insert into SKILL (S_ID, Skill_Name) values (23, 'HMI Configuration');
insert into SKILL (S_ID, Skill_Name) values (24, 'EEO Reporting');
insert into SKILL (S_ID, Skill_Name) values (25, 'Mutual Funds');
insert into SKILL (S_ID, Skill_Name) values (26, 'Foreign Languages');
insert into SKILL (S_ID, Skill_Name) values (27, 'OSHA 30-Hour');
insert into SKILL (S_ID, Skill_Name) values (28, 'Omnet++');
insert into SKILL (S_ID, Skill_Name) values (29, 'Music Theory');
insert into SKILL (S_ID, Skill_Name) values (30, 'Non-fiction');
insert into SKILL (S_ID, Skill_Name) values (31, 'OS X');
insert into SKILL (S_ID, Skill_Name) values (32, 'MVPN');
insert into SKILL (S_ID, Skill_Name) values (33, 'Medical Billing');
insert into SKILL (S_ID, Skill_Name) values (34, 'QRC');
insert into SKILL (S_ID, Skill_Name) values (35, 'CAD');
insert into SKILL (S_ID, Skill_Name) values (36, 'Call center start-up');
insert into SKILL (S_ID, Skill_Name) values (37, 'Lync');
insert into SKILL (S_ID, Skill_Name) values (38, 'JCT');
insert into SKILL (S_ID, Skill_Name) values (39, 'IBM pSeries');
insert into SKILL (S_ID, Skill_Name) values (40, 'Zoology');
insert into SKILL (S_ID, Skill_Name) values (41, 'Groundwater');
insert into SKILL (S_ID, Skill_Name) values (42, 'JIS');
insert into SKILL (S_ID, Skill_Name) values (43, 'Reaction Kinetics');
insert into SKILL (S_ID, Skill_Name) values (44, 'Luxury Lifestyle');
insert into SKILL (S_ID, Skill_Name) values (45, 'Product Life Cycle');
insert into SKILL (S_ID, Skill_Name) values (46, 'JFace');
insert into SKILL (S_ID, Skill_Name) values (47, 'Knitwear');
insert into SKILL (S_ID, Skill_Name) values (48, 'PMM');
insert into SKILL (S_ID, Skill_Name) values (49, 'Android');
insert into SKILL (S_ID, Skill_Name) values (50, 'UDP');
insert into SKILL (S_ID, Skill_Name) values (51, 'LSAT');
insert into SKILL (S_ID, Skill_Name) values (52, 'Security');
insert into SKILL (S_ID, Skill_Name) values (53, 'ETABS');
insert into SKILL (S_ID, Skill_Name) values (54, 'Blood Typing');
insert into SKILL (S_ID, Skill_Name) values (55, 'NS-2');
insert into SKILL (S_ID, Skill_Name) values (56, 'Ethernet over Copper');
insert into SKILL (S_ID, Skill_Name) values (57, 'Brazilian Jiu-Jitsu');
insert into SKILL (S_ID, Skill_Name) values (58, 'PPPoA');
insert into SKILL (S_ID, Skill_Name) values (59, 'Visual Basic');
insert into SKILL (S_ID, Skill_Name) values (60, 'RNA Biology');
insert into SKILL (S_ID, Skill_Name) values (61, 'Electronic Payments');
insert into SKILL (S_ID, Skill_Name) values (62, 'Telecommunications');
insert into SKILL (S_ID, Skill_Name) values (63, 'Offshore Outsourcing');
insert into SKILL (S_ID, Skill_Name) values (64, 'RTL Verification');
insert into SKILL (S_ID, Skill_Name) values (65, 'Lua');
insert into SKILL (S_ID, Skill_Name) values (66, 'Two-factor Authentication');
insert into SKILL (S_ID, Skill_Name) values (67, 'EIM');
insert into SKILL (S_ID, Skill_Name) values (68, 'HDI');
insert into SKILL (S_ID, Skill_Name) values (69, 'Quantity Surveying');
insert into SKILL (S_ID, Skill_Name) values (70, 'LNA');
insert into SKILL (S_ID, Skill_Name) values (71, 'MSS');
insert into SKILL (S_ID, Skill_Name) values (72, 'GSX');
insert into SKILL (S_ID, Skill_Name) values (73, 'Cyber Defense');
insert into SKILL (S_ID, Skill_Name) values (74, 'Gift Tax');
insert into SKILL (S_ID, Skill_Name) values (75, 'Zope');
insert into SKILL (S_ID, Skill_Name) values (76, 'Solvency II');
insert into SKILL (S_ID, Skill_Name) values (77, 'Fashion GPS');
insert into SKILL (S_ID, Skill_Name) values (78, 'Microsoft SQL Server');
insert into SKILL (S_ID, Skill_Name) values (79, 'Site Development');
insert into SKILL (S_ID, Skill_Name) values (80, 'Underwriting');
insert into SKILL (S_ID, Skill_Name) values (81, 'NMR Spectroscopy');
insert into SKILL (S_ID, Skill_Name) values (82, 'Solution Architecture');
insert into SKILL (S_ID, Skill_Name) values (83, 'VMware ESX');
insert into SKILL (S_ID, Skill_Name) values (84, 'FX Operations');
insert into SKILL (S_ID, Skill_Name) values (85, 'White Collar Criminal Defense');
insert into SKILL (S_ID, Skill_Name) values (86, 'Digital Illustration');
insert into SKILL (S_ID, Skill_Name) values (87, 'Software Implementation');
insert into SKILL (S_ID, Skill_Name) values (88, 'Outpatient Orthopedics');
insert into SKILL (S_ID, Skill_Name) values (89, 'RFI');
insert into SKILL (S_ID, Skill_Name) values (90, 'White Box Testing');
insert into SKILL (S_ID, Skill_Name) values (91, 'Sustainable Design');
insert into SKILL (S_ID, Skill_Name) values (92, 'VPM');
insert into SKILL (S_ID, Skill_Name) values (93, 'CBORD');
insert into SKILL (S_ID, Skill_Name) values (94, 'Merchandising');
insert into SKILL (S_ID, Skill_Name) values (95, 'Interviewing Skills');
insert into SKILL (S_ID, Skill_Name) values (96, 'SFR Certified');
insert into SKILL (S_ID, Skill_Name) values (97, 'Jitterbit');
insert into SKILL (S_ID, Skill_Name) values (98, 'Financial Mgmt');
insert into SKILL (S_ID, Skill_Name) values (99, 'Direct Marketing');
insert into SKILL (S_ID, Skill_Name) values (100, 'LTACH');
